/**
 * Automation Utilities
 * 
 * Client-side automation functions that can be triggered by:
 * - Firestore listeners (onSnapshot)
 * - Manual admin actions
 * - Scheduled checks (when app is open)
 * 
 * For scheduled tasks (monthly invoices, daily reminders), see:
 * - Firebase Functions setup in functions/ directory
 * - Or use client-side scheduled checks when admin dashboard is open
 */

import { db } from './firebase';
import {
  collection,
  addDoc,
  updateDoc,
  doc,
  query,
  where,
  getDocs,
  serverTimestamp,
  Timestamp,
} from 'firebase/firestore';
import { logActivity } from './activityLogger';
import { sendNotificationEmail } from './email';

// ── Types ────────────────────────────────────────────────────────────────────

interface WeeklyPlan {
  id: string;
  clientId: string;
  weeks: Array<{
    weekNumber: number;
    weekLabel: string;
    tasks: string[];
  }>;
}

interface Client {
  id: string;
  email?: string;
  businessName?: string;
  status?: string;
  projectStatus?: string;
  onboardingCompleted?: boolean;
  budget?: string;
}

interface Invoice {
  id: string;
  clientId?: string;
  clientName: string;
  clientEmail?: string;
  amount: number;
  status: 'pending' | 'paid' | 'overdue';
  month: string;
  dueDate?: string;
  createdAt?: Timestamp;
}

// ── Budget to Amount Mapping ────────────────────────────────────────────────

const BUDGET_AMOUNTS: Record<string, number> = {
  starter: 750,      // Average of ₹500-₹1,000
  growth: 2000,      // Average of ₹1,000-₹3,000
  scale: 4000,       // Average of ₹3,000-₹5,000
  enterprise: 6000,  // Average of ₹5,000+
};

// ── 1. Automated Task Generation from Weekly Plans ──────────────────────────

/**
 * Auto-generate tasks from a weekly plan
 * Called when weekly plan is created or updated
 */
export async function autoGenerateTasksFromWeeklyPlan(
  clientId: string,
  weeklyPlan: WeeklyPlan
): Promise<{ created: number; skipped: number }> {
  if (!weeklyPlan.weeks || weeklyPlan.weeks.length === 0) {
    return { created: 0, skipped: 0 };
  }

  let created = 0;
  let skipped = 0;

  try {
    // Get existing tasks for this client
    const existingTasksQuery = query(
      collection(db, 'tasks'),
      where('clientId', '==', clientId)
    );
    const existingTasksSnap = await getDocs(existingTasksQuery);
    const existingTasks = existingTasksSnap.docs.map(d => ({
      id: d.id,
      ...d.data(),
    }));

    // Generate tasks for each week
    for (const week of weeklyPlan.weeks) {
      for (const taskTitle of week.tasks) {
        if (!taskTitle.trim()) continue;

        // Check if task already exists
        const exists = existingTasks.some(
          (t: any) =>
            t.clientId === clientId &&
            t.title === taskTitle.trim() &&
            t.week === week.weekLabel
        );

        if (!exists) {
          await addDoc(collection(db, 'tasks'), {
            title: taskTitle.trim(),
            priority: 'medium',
            status: 'todo',
            clientId: clientId,
            week: week.weekLabel,
            createdAt: serverTimestamp(),
            createdBy: 'automation',
            autoGenerated: true,
          });
          created++;
        } else {
          skipped++;
        }
      }
    }

    if (created > 0) {
      await logActivity({
        type: 'task_created',
        title: `${created} task${created > 1 ? 's' : ''} auto-generated from weekly plan`,
        subtitle: `Client: ${clientId}`,
        clientId: clientId,
        metadata: { taskCount: created, fromWeeklyPlan: true, autoGenerated: true },
      });
    }
  } catch (error) {
    console.error('Error auto-generating tasks:', error);
    throw error;
  }

  return { created, skipped };
}

// ── 2. Automated Invoice Generation ───────────────────────────────────────────

/**
 * Generate monthly invoices for all active clients
 * Should be called on the 1st of each month (via Firebase Functions or manual trigger)
 */
export async function autoGenerateMonthlyInvoices(
  month?: string
): Promise<{ created: number; skipped: number }> {
  const now = new Date();
  const invoiceMonth = month || now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
  const dueDate = new Date(now.getFullYear(), now.getMonth(), 15).toLocaleDateString();

  let created = 0;
  let skipped = 0;

  try {
    // Get all active clients
    const clientsQuery = query(
      collection(db, 'clients'),
      where('projectStatus', '==', 'Active')
    );
    const clientsSnap = await getDocs(clientsQuery);
    const clients = clientsSnap.docs.map(d => ({
      id: d.id,
      ...d.data(),
    })) as Client[];

    // Get existing invoices for this month
    const invoicesQuery = query(
      collection(db, 'invoices'),
      where('month', '==', invoiceMonth)
    );
    const invoicesSnap = await getDocs(invoicesQuery);
    const existingClientIds = new Set(
      invoicesSnap.docs
        .map(d => d.data().clientId || d.data().clientEmail)
        .filter(Boolean)
    );

    // Generate invoices
    for (const client of clients) {
      // Skip if invoice already exists
      if (
        existingClientIds.has(client.id) ||
        (client.email && existingClientIds.has(client.email))
      ) {
        skipped++;
        continue;
      }

      // Calculate invoice amount from budget
      const amount = client.budget ? BUDGET_AMOUNTS[client.budget] || 1000 : 1000;

      await addDoc(collection(db, 'invoices'), {
        clientName: client.businessName || client.email || 'Client',
        clientEmail: client.email,
        clientId: client.id,
        amount: amount,
        status: 'pending',
        month: invoiceMonth,
        dueDate: dueDate,
        createdAt: serverTimestamp(),
        autoGenerated: true,
      });

      await logActivity({
        type: 'invoice_created',
        title: `Invoice auto-generated for ${client.businessName || client.email}`,
        subtitle: `Amount: ₹${amount}, Month: ${invoiceMonth}`,
        clientId: client.id,
        metadata: { amount, month: invoiceMonth, autoGenerated: true },
      });

      // Send email notification
      await sendNotificationEmail(client.id, 'invoice_created', {
        invoiceId: 'auto-generated',
        amount,
        month: invoiceMonth,
        dueDate,
        status: 'pending',
      });

      created++;
    }
  } catch (error) {
    console.error('Error auto-generating invoices:', error);
    throw error;
  }

  return { created, skipped };
}

// ── 3. Automated Payment Reminders ───────────────────────────────────────────

/**
 * Check for overdue invoices and send reminders
 * Should be called daily (via Firebase Functions or manual trigger)
 */
export async function checkAndSendPaymentReminders(): Promise<{
  remindersSent: number;
  overdueUpdated: number;
}> {
  let remindersSent = 0;
  let overdueUpdated = 0;

  try {
    const now = new Date();
    const today = now.toISOString().split('T')[0];

    // Get all pending invoices
    const invoicesQuery = query(
      collection(db, 'invoices'),
      where('status', '==', 'pending')
    );
    const invoicesSnap = await getDocs(invoicesQuery);
    const invoices = invoicesSnap.docs.map(d => ({
      id: d.id,
      ...d.data(),
    })) as Invoice[];

    for (const invoice of invoices) {
      if (!invoice.dueDate) continue;

      const dueDate = new Date(invoice.dueDate);
      const daysUntilDue = Math.ceil(
        (dueDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)
      );
      const daysOverdue = -daysUntilDue;

      // Update to overdue if past due date
      if (daysOverdue > 0 && invoice.status === 'pending') {
        await updateDoc(doc(db, 'invoices', invoice.id), {
          status: 'overdue',
        });

        await logActivity({
          type: 'invoice_created', // Using existing type
          title: `Invoice marked as overdue: ${invoice.clientName}`,
          subtitle: `Amount: ₹${invoice.amount}, ${daysOverdue} day${daysOverdue > 1 ? 's' : ''} overdue`,
          clientId: invoice.clientId || '',
          metadata: { invoiceId: invoice.id, daysOverdue },
        });

        overdueUpdated++;
      }

      // Send reminders based on timing
      if (daysUntilDue === 3 || daysUntilDue === 0 || daysOverdue === 3 || daysOverdue === 7) {
        await logActivity({
          type: 'invoice_created', // Using existing type
          title: `Payment reminder: ${invoice.clientName}`,
          subtitle: `Invoice ${invoice.month} - ₹${invoice.amount} ${daysOverdue > 0 ? `(${daysOverdue} days overdue)` : `(due in ${daysUntilDue} days)`}`,
          clientId: invoice.clientId || '',
          metadata: { invoiceId: invoice.id, reminderType: daysUntilDue === 3 ? 'before' : daysOverdue > 0 ? 'overdue' : 'due' },
        });

        // Send email reminder
        if (invoice.clientId) {
          await sendNotificationEmail(invoice.clientId, 'payment_reminder', {
            invoiceId: invoice.id,
            amount: invoice.amount,
            month: invoice.month,
            dueDate: invoice.dueDate,
            daysUntilDue,
            daysOverdue,
          });
        }

        remindersSent++;
      }
    }
  } catch (error) {
    console.error('Error checking payment reminders:', error);
    throw error;
  }

  return { remindersSent, overdueUpdated };
}

// ── 4. Automated Client Status Transitions ───────────────────────────────────

/**
 * Auto-update client status based on workflow
 * Called when client data changes
 */
export async function autoUpdateClientStatus(clientId: string, client: Client): Promise<{
  statusChanged: boolean;
  newStatus?: string;
}> {
  try {
    let newStatus: string | undefined;
    let projectStatus: string | undefined;
    let onboardingCompleted: boolean | undefined;

    // Rule 1: Onboarding complete → Planning
    if (client.onboardingCompleted && client.projectStatus === 'Strategy') {
      newStatus = 'planning';
      projectStatus = 'Planning';
      onboardingCompleted = true;
    }
    // Rule 2: Plan created → Active
    else if (client.projectStatus === 'Planning') {
      // Check if marketing plan exists
      const planQuery = query(
        collection(db, 'marketingPlans'),
        where('clientId', '==', clientId)
      );
      const planSnap = await getDocs(planQuery);
      
      if (!planSnap.empty) {
        newStatus = 'active';
        projectStatus = 'Active';
        onboardingCompleted = true;
      }
    }
    // Rule 3: No activity for 60 days → Paused
    else if (client.projectStatus === 'Active') {
      const clientDoc = await getDocs(query(
        collection(db, 'clients'),
        where('__name__', '==', clientId)
      ));
      
      if (!clientDoc.empty) {
        const clientData = clientDoc.docs[0].data();
        const updatedAt = clientData.updatedAt as Timestamp | undefined;
        
        if (updatedAt) {
          const daysSinceUpdate = (Date.now() - updatedAt.toMillis()) / (1000 * 60 * 60 * 24);
          
          if (daysSinceUpdate > 60) {
            newStatus = 'paused';
            projectStatus = 'Paused';
          }
        }
      }
    }

    // Update status if changed
    if (newStatus) {
      const updateData: any = {
        updatedAt: serverTimestamp(),
      };

      if (projectStatus !== undefined) {
        updateData.projectStatus = projectStatus;
      }
      if (onboardingCompleted !== undefined) {
        updateData.onboardingCompleted = onboardingCompleted;
      }

      await updateDoc(doc(db, 'clients', clientId), updateData);

      await logActivity({
        type: 'status_change',
        title: `Status auto-updated to "${newStatus}"`,
        subtitle: `Client: ${client.businessName || client.email || clientId}`,
        clientId: clientId,
        metadata: { newStatus, autoUpdated: true },
      });

      return { statusChanged: true, newStatus };
    }

    return { statusChanged: false };
  } catch (error) {
    console.error('Error auto-updating client status:', error);
    throw error;
  }
}

// ── 5. Automated Onboarding Task Assignment ──────────────────────────────────

/**
 * Auto-assign initial tasks when onboarding is completed
 * Called when onboardingCompleted changes to true
 */
export async function autoAssignOnboardingTasks(
  clientId: string,
  client: Client
): Promise<{ created: number }> {
  let created = 0;

  try {
    // Check if tasks already exist for this client
    const existingTasksQuery = query(
      collection(db, 'tasks'),
      where('clientId', '==', clientId)
    );
    const existingTasksSnap = await getDocs(existingTasksQuery);

    if (!existingTasksSnap.empty) {
      // Tasks already exist, skip
      return { created: 0 };
    }

    // Default onboarding tasks
    const onboardingTasks = [
      'Review marketing strategy',
      'Complete business profile',
      'Set up initial goals',
      'Schedule kickoff meeting',
    ];

    // Create tasks
    for (const taskTitle of onboardingTasks) {
      await addDoc(collection(db, 'tasks'), {
        title: taskTitle,
        priority: 'high',
        status: 'todo',
        clientId: clientId,
        createdAt: serverTimestamp(),
        createdBy: 'automation',
        autoGenerated: true,
        isOnboardingTask: true,
      });
      created++;
    }

    if (created > 0) {
      await logActivity({
        type: 'task_created',
        title: `${created} onboarding task${created > 1 ? 's' : ''} auto-assigned`,
        subtitle: `Client: ${client.businessName || client.email || clientId}`,
        clientId: clientId,
        metadata: { taskCount: created, autoGenerated: true, isOnboardingTask: true },
      });
    }
  } catch (error) {
    console.error('Error auto-assigning onboarding tasks:', error);
    throw error;
  }

  return { created };
}

// ── Helper: Check for Weekly Plan Updates ────────────────────────────────────

/**
 * Monitor weekly plan changes and auto-generate tasks
 * Should be called from a Firestore listener
 */
export async function handleWeeklyPlanUpdate(
  weeklyPlanId: string,
  weeklyPlanData: WeeklyPlan
): Promise<void> {
  try {
    await autoGenerateTasksFromWeeklyPlan(weeklyPlanData.clientId, weeklyPlanData);
  } catch (error) {
    console.error('Error handling weekly plan update:', error);
  }
}

// ── Helper: Check for Client Updates ─────────────────────────────────────────

/**
 * Monitor client changes and auto-update status or assign tasks
 * Should be called from a Firestore listener
 */
export async function handleClientUpdate(
  clientId: string,
  clientData: Client,
  previousData?: Client
): Promise<void> {
  try {
    // Check if onboarding was just completed
    if (
      clientData.onboardingCompleted &&
      (!previousData || !previousData.onboardingCompleted)
    ) {
      await autoAssignOnboardingTasks(clientId, clientData);
    }

    // Auto-update status
    await autoUpdateClientStatus(clientId, clientData);
  } catch (error) {
    console.error('Error handling client update:', error);
  }
}

